# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
# DE Sites    
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  logoUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/refs/heads/master/assets/changan-logo.svg
  name: Changan Europe Status
  themeUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/refs/heads/master/assets/customTheme.css
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: UK
      href: https://www.changaneurope.com/uk/
    - title: DE
      href: https://www.changaneurope.com/de/
    - title: NL
      href: https://www.changaneurope.com/nl/
css: |
    :root {
      --primary-color: #002b5c;
      --nav-background-color: #002b5c;
      --nav-text-color: #ffffff;
      --body-background-color: #ffffff;
    }

    /* Force page background to white */
    body, #sapper {
      background-color: #ffffff !important;
    }

    /* 1. Navigation Bar Styling (Blue Background) */
    nav {
      background-color: var(--nav-background-color) !important;
      padding: 15px 0 !important;
      position: relative !important;
      display: flex !important;
      justify-content: center !important;
    }

    /* Standardizes the internal container for mobile spacing */
    nav .container {
      display: flex !important;
      align-items: center !important;
      justify-content: space-between !important; 
      width: 100% !important;
      max-width: 1200px !important;
      padding: 0 20px !important;
    }

    /* 2. Responsive Logo Styling */
    nav .logo {
      display: flex !important;
      align-items: center !important;
      text-decoration: none !important;
      /* Removes absolute positioning on mobile to prevent overlap */
      position: relative !important; 
      left: 0 !important;
      transform: none !important;
      top: 0 !important;
    }

    nav .logo div {
      display: none !important; /* Hides "Changan Europe Status" text */
    }

    nav .logo img {
      /* Fluid width: Min 120px, scales with screen, Max 220px */
      width: clamp(120px, 30vw, 220px) !important; 
      height: auto !important;
      display: block !important;
      filter: brightness(0) invert(1) !important;
    }

    /* 3. White Navigation Links */
    #sapper > nav ul {
      display: flex !important;
      list-style: none !important;
      margin: 0 !important;
      padding: 0 !important;
    }

    #sapper > nav ul li a {
      color: #ffffff !important; /* Explicitly forces white links */
      font-weight: bold !important;
      margin-left: 15px !important;
      text-decoration: none !important;
      font-size: 0.9rem !important;
    }

    /* 4. Desktop Adjustments (Screens wider than 768px) */
    @media (min-width: 768px) {
      nav .logo {
        position: absolute !important;
        left: 20px !important;
        top: 50% !important;
        transform: translateY(-50%) !important;
      }
      
      #sapper > nav ul li a {
        margin: 0 20px !important;
        font-size: 1rem !important;
      }
    }

    /* 5. Blue Service Monitor Box (Original Design) */
    header {
      background-color: #ffffff !important;
      padding: 60px 0 !important;
    }

    header h1, header p {
      background-color: var(--nav-background-color) !important;
      color: #ffffff !important;
      margin: 0 auto !important;
      max-width: 900px !important;
      text-align: center !important;
    }

    header h1 {
      padding: 40px 60px 10px 60px !important;
      border-radius: 8px 8px 0 0 !important;
      font-size: 2.2rem !important;
    }

    header p {
      padding: 0 60px 40px 60px !important;
      border-radius: 0 0 8px 8px !important;
      font-size: 1.1rem !important;
    }
