# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
 # DE Sites   
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  logoUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/master/assets/changan-logo-white.svg
  name: Changan Europe Status
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: UK
      href: https://www.changaneurope.com/uk/
    - title: DE
      href: https://www.changaneurope.com/de/
    - title: NL
      href: https://www.changaneurope.com/nl/
css: |
    :root {
      --primary-color: #002b5c;
      --nav-background-color: #002b5c;
      --nav-text-color: #ffffff;
      --body-background-color: #ffffff;
    }

    /* Fix for the Body Background */
    body, #sapper {
      background-color: #ffffff !important;
    }

    /* Navbar Styling */
    nav {
      background-color: var(--nav-background-color) !important;
      position: relative !important;
      display: flex !important;
      justify-content: center !important;
      padding: 15px 0 !important;
    }

    /* Container alignment for center links */
    nav .container {
      display: flex !important;
      justify-content: center !important;
      width: 100% !important;
      max-width: none !important;
    }

    /* Logo Positioning - Left Side */
    nav .logo {
      position: absolute !important;
      left: 40px !important;
      top: 50% !important;
      transform: translateY(-50%) !important;
      display: flex !important;
      align-items: center !important;
    }

    /* Hide the text next to the logo */
    nav .logo div {
      display: none !important;
    }

    /* Force the Logo Image to be visible and white */
    nav .logo img {
      height: 32px !important; /* Increased height for better visibility */
      width: auto !important;
      display: block !important;
      /* Ensuring it appears white regardless of the source SVG state */
      filter: brightness(0) invert(1) !important; 
    }

    /* Navbar Links (UK, DE, NL) */
    nav ul {
      display: flex !important;
      margin: 0 !important;
      padding: 0 !important;
      list-style: none !important;
    }

    nav ul li a {
      color: #ffffff !important;
      font-weight: bold !important;
      margin: 0 20px !important;
      text-decoration: none !important;
    }

    /* Restore the Blue Header Box */
    header.svelte-ngkazm {
      background-color: transparent !important;
      padding: 40px 0 !important;
    }

    header h1, header p {
      background-color: var(--nav-background-color) !important;
      color: #ffffff !important;
      margin: 0 auto !important;
      max-width: 800px !important;
      text-align: center !important;
    }

    header h1 {
      padding: 40px 40px 10px 40px !important;
      border-radius: 8px 8px 0 0 !important;
    }

    header p {
      padding: 0 40px 40px 40px !important;
      border-radius: 0 0 8px 8px !important;
    }
