# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
# DE Sites     
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  logoUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/refs/heads/master/assets/changan-logo.svg
  name: Changan Europe Status
  themeUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/refs/heads/master/assets/customTheme.css
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: UK
      href: https://www.changaneurope.com/uk/
      target: _top
    - title: DE
      href: https://www.changaneurope.com/de/
      target: _top
    - title: NL
      href: https://www.changaneurope.com/nl/
      target: _top
css: |
    :root {
      --primary-color: #002b5c;
      --nav-background-color: #002b5c;
      --nav-text-color: #ffffff;
      --body-background-color: #ffffff;
    }

    /* FIX: Force white background to prevent theme fallback */
    body, #sapper {
      background-color: #ffffff !important;
    }

    /* 1. Navbar & Logo Fix */
    nav {
      justify-content: flex-end !important; 
      padding: 15px 20px !important;
      position: relative !important;
      display: flex !important;
      align-items: center !important;
      min-height: 60px !important;
    }

    nav .logo {
      position: absolute !important;
      left: 20px !important;
      top: 50% !important;
      transform: translateY(-50%) !important;
      display: flex !important;
      align-items: center !important;
      /* Restrict logo width on mobile so it doesn't hit links */
      max-width: 45% !important; 
    }

    nav .logo div {
      display: none !important;
    }

    /* Force the SVG to be responsive and white */
    nav .logo img {
      width: 100% !important; 
      max-width: 250px !important; 
      height: auto !important;
      display: block !important;
      filter: brightness(0) invert(1) !important;
    }

    /* 2. Navigation Links */
    #sapper > nav ul {
      display: flex !important;
      list-style: none !important;
      margin: 0 !important;
      padding: 0 !important;
      margin-left: auto !important;
      z-index: 10 !important;
    }

    #sapper > nav ul li {
      display: flex !important;
    }

    #sapper > nav ul li a {
      color: #ffffff !important; 
      font-weight: bold !important;
      /* Responsive spacing between links */
      margin-left: clamp(10px, 2vw, 20px) !important; 
      text-decoration: none !important;
      /* Responsive font size */
      font-size: clamp(0.75rem, 2.5vw, 1rem) !important; 
      white-space: nowrap !important;
    }

    /* 3. Header Styling */
    header {
      background-color: #ffffff !important;
      padding: 60px 0 !important;
      display: block !important;
      visibility: visible !important;
    }

    header h1, header p {
      background-color: var(--nav-background-color) !important;
      color: #ffffff !important;
      margin: 0 auto !important;
      max-width: 900px !important;
      text-align: center !important;
    }

    header h1 {
      padding: 40px 60px 10px 60px !important;
      border-radius: 8px 8px 0 0 !important;
      font-size: 2.2rem !important;
    }

    header p {
      padding: 0 60px 40px 60px !important;
      border-radius: 0 0 8px 8px !important;
      font-size: 1.1rem !important;
    }
    
    nav a:not(.logo) {
      font-weight: bold !important;
    }
