# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
 # DE Sites   
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  logoUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/master/assets/changan-logo-white.svg
  name: Changan Europe Status
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: UK
      href: https://www.changaneurope.com/uk/
    - title: DE
      href: https://www.changaneurope.com/de/
    - title: NL
      href: https://www.changaneurope.com/nl/
css: |
    :root {
      --primary-color: #002b5c;
      --nav-background-color: #002b5c;
      --nav-text-color: #ffffff;
      --body-background-color: #ffffff;
    }

    /* Navbar Container Setup */
    nav {
      position: relative !important;
      display: flex !important;
      justify-content: center !important; /* Centers the UK/DE/NL links */
      padding: 20px 0 !important;
      height: 70px !important; /* Set a fixed height for consistency */
    }

    /* 1. Logo Positioning (Left Aligned) */
    nav .logo {
      position: absolute !important;
      left: 30px !important;
      top: 50% !important;
      transform: translateY(-50%) !important;
      display: flex !important;
      align-items: center !important;
      text-decoration: none !important;
    }

    /* 2. Hide the "Changan Europe Status" text next to the logo */
    nav .logo div {
      display: none !important;
    }

    /* 3. Logo Image Sizing */
    nav .logo img {
      height: 22px !important; /* Adjusted to look like the main site */
      width: auto !important;
      /* If using the white SVG version, we don't need the filter, 
         but keeping it as a safety measure won't hurt */
      filter: brightness(0) invert(1) !important; 
    }

    /* 4. Navigation Links (UK, DE, NL) */
    nav ul {
      margin: 0 !important;
      padding: 0 !important;
      list-style: none !important;
      display: flex !important;
    }

    nav a:not(.logo) {
      font-weight: 700 !important;
      margin: 0 25px !important;
      font-size: 14px !important;
      text-transform: uppercase !important;
      letter-spacing: 1px !important;
    }

    /* 5. Header / Intro Box Styling */
    header {
      background-color: #ffffff !important;
      padding: 60px 0 !important;
    }

    header h1, header p {
      background-color: var(--nav-background-color) !important;
      color: #ffffff !important;
      margin: 0 auto !important;
      max-width: 900px !important;
      text-align: center !important;
    }

    header h1 {
      padding: 45px 60px 10px 60px !important;
      border-radius: 12px 12px 0 0 !important;
      font-size: 2.2rem !important;
    }

    header p {
      padding: 0 60px 45px 60px !important;
      border-radius: 0 0 12px 12px !important;
      font-size: 1.1rem !important;
      line-height: 1.6 !important;
    }
