# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
 # DE Sites   
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  logoUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/master/assets/changan-logo-white.svg
  name: Changan Europe Status
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: UK
      href: https://www.changaneurope.com/uk/
    - title: DE
      href: https://www.changaneurope.com/de/
    - title: NL
      href: https://www.changaneurope.com/nl/
css: |
    /* 1. Global Reset to Light Mode */
    :root, html, body, #sapper {
      --body-background-color: #ffffff !important;
      background-color: #ffffff !important;
      color: #333333 !important;
    }

    /* 2. Navbar & Logo Alignment */
    nav.svelte-a08hsz {
      background-color: #002b5c !important;
      padding: 15px 0 !important;
      position: relative !important;
      display: flex !important;
      justify-content: center !important;
      border-bottom: none !important;
    }

    nav .container {
      display: flex !important;
      justify-content: center !important;
      align-items: center !important;
      width: 100% !important;
      max-width: 1200px !important;
    }

    /* Positioning the logo on the far left */
    nav .logo {
      position: absolute !important;
      left: 20px !important;
      display: flex !important;
      align-items: center !important;
    }

    /* Hide the text "Changan Europe Status" next to the logo */
    nav .logo div {
      display: none !important;
    }

    /* Adjust the SVG logo size and visibility */
    nav .logo img {
      height: 35px !important; /* Increased for visibility */
      width: auto !important;
      filter: brightness(0) invert(1) !important; /* Forces it to white */
      opacity: 1 !important;
      display: block !important;
    }

    /* 3. Navbar Links (UK, DE, NL) */
    nav ul {
      display: flex !important;
      list-style: none !important;
      margin: 0 !important;
      padding: 0 !important;
    }

    nav ul li a {
      color: #ffffff !important;
      font-weight: bold !important;
      margin: 0 20px !important;
      text-decoration: none !important;
      font-size: 1rem !important;
    }

    /* 4. Restore Blue Header "Box" */
    header.svelte-ngkazm {
      background-color: transparent !important;
      padding: 60px 0 20px 0 !important;
      display: flex !important;
      flex-direction: column !important;
      align-items: center !important;
    }

    header h1 {
      background-color: #002b5c !important;
      color: #ffffff !important;
      margin: 0 !important;
      padding: 60px 80px 10px 80px !important;
      border-radius: 12px 12px 0 0 !important;
      width: 100% !important;
      max-width: 800px !important;
      text-align: center !important;
    }

    header p.lead {
      background-color: #002b5c !important;
      color: #ffffff !important;
      margin: 0 !important;
      padding: 0 80px 60px 80px !important;
      border-radius: 0 0 12px 12px !important;
      width: 100% !important;
      max-width: 800px !important;
      text-align: center !important;
      line-height: 1.6 !important;
    }

    /* 5. Live Status & Tables Reset */
    .live-status, article.up, h2 {
      color: #333333 !important;
    }
