# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
 # DE Sites   
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  logoUrl: https://www.changaneurope.com/static/version1709633634/frontend/Changan/default/en_GB/images/logo.svg
  name: Changan Europe Status
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: Status
      href: /
    - title: Changan Europe
      href: https://www.changaneurope.com/uk/
  css: |
    :root {
      /* Brand Colors */
      --primary-color: #002b5c; /* Changan Deep Blue */
      --body-background-color: #f8f9fa;
      --card-background-color: #ffffff;
      --nav-background-color: #002b5c;
      --nav-text-color: #ffffff;
      --body-text-color: #1a1a1a;
      
      /* Status Indicators */
      --status-up: #28a745;
      --status-down: #dc3545;
      --status-degraded: #ffc107;
    }

    /* Typography & Header */
    body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }
    
    header { 
      background-color: var(--nav-background-color); 
      padding: 3rem 0;
      border-bottom: 4px solid #001f42;
    }
    
    header h1, header p { color: white; text-align: center; }

    /* Modern Card Layout */
    .card {
      border: 1px solid #e1e4e8;
      border-radius: 8px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
      transition: transform 0.2s ease-in-out;
      margin-bottom: 1.5rem;
    }

    .card:hover {
      transform: translateY(-2px);
      box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1);
    }

    /* Progress & Uptime Bars */
    .progress-bar { border-radius: 4px; height: 8px; }
    
    /* Tables & Links */
    table { width: 100%; border-collapse: separate; border-spacing: 0 10px; }
    th { color: var(--primary-color); text-transform: uppercase; font-size: 0.8rem; letter-spacing: 1px; }
    a { color: var(--primary-color); font-weight: 600; text-decoration: none; }
    a:hover { text-decoration: underline; }
