# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
 # DE Sites   
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  # Points to the white version of the logo in your assets folder
  logoUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/master/assets/changan-logo-white.svg
  # This name will now be hidden by CSS to clean up the navbar
  name: Changan Europe Status
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: UK
      href: https://www.changaneurope.com/uk/
    - title: DE
      href: https://www.changaneurope.com/de/
    - title: NL
      href: https://www.changaneurope.com/nl/
  css: |
    :root {
      --primary-color: #002b5c;
      --nav-background-color: #002b5c;
      --nav-text-color: #ffffff;
      --body-background-color: #ffffff; /* Restores white background */
    }

    /* 1. Logo Position (Top Left) */
    .nav-logo {
      position: absolute;
      left: 20px;
      height: 30px;
      top: 50%;
      transform: translateY(-50%);
    }

    /* 2. Remove "Changan Europe Status" text from navbar */
    nav h1, nav .repo-name { 
      display: none !important; 
    }

    /* 3. Navbar Styling (Centered buttons) */
    nav {
      display: flex;
      justify-content: center;
      padding: 15px 0;
      position: relative;
    }

    nav a {
      color: white !important;
      font-weight: bold !important;
      margin: 0 20px;
      text-transform: uppercase;
      font-size: 14px;
    }

    /* 4. Centered Blue Header Box with Padding */
    header {
      background-color: transparent; /* Makes the full-width header invisible */
      padding: 50px 0;
    }

    header .container {
      background-color: var(--nav-background-color);
      padding: 40px 60px; /* Internal padding for text */
      border-radius: 4px;
      max-width: 900px;
      margin: 0 auto;
      text-align: center;
    }

    header h1, header p { 
      color: white !important; 
      margin: 10px 0;
    }

    /* Card styling adjustment for white background */
    .card {
      background-color: #ffffff;
      border: 1px solid #eee;
      margin-top: 20px;
    }
