# Change these first
owner: LV-CMilne # Your GitHub organization or username, where this repository lives
repo: ChanganUpptime-v1 # The name of this repository

sites:
# UK Sites
  - name: Changan UK
    url: https://www.changaneurope.com/uk
  - name: Changan UK - Contact
    url: https://www.changaneurope.com/uk/contact-us
  - name: Changan UK - Privacy Policy
    url: https://www.changaneurope.com/uk/privacy-policy
  - name: Changan UK - Configurator
    url: https://www.changaneurope.com/uk/configurator  
  - name: Changan UK - Book a Test Drive
    url: https://www.changaneurope.com/uk/models/changan-deepal-s07/test-drive
 # DE Sites   
  - name: Changan DE
    url: https://www.changaneurope.com/de
  - name: Changan DE - Contact
    url: https://www.changaneurope.com/de/kontakt
  - name: Changan DE - Privacy Policy
    url: https://www.changaneurope.com/de/datenschutzerklarung
  - name: Changan DE - Configurator
    url: https://www.changaneurope.com/de/modellauswahl 
  - name: Changan DE - Book a Test Drive
    url: https://www.changaneurope.com/de/probefahrt
  # NL Sites  
  - name: Changan NL
    url: https://www.changaneurope.com/nl
  - name: Changan NL - Contact
    url: https://www.changaneurope.com/nl/contact
  - name: Changan NL - Privacy Policy
    url: https://www.changaneurope.com/nl/privacybeleid
  - name: Changan NL - Configurator
    url: https://www.changaneurope.com/nl/model-chooser  
  - name: Changan NL - Book a Test Drive
    url: https://www.changaneurope.com/nl/proefrit

    
status-website:
  baseUrl: /ChanganUpptime-v1
  logoUrl: https://raw.githubusercontent.com/LV-CMilne/ChanganUpptime-v1/master/assets/changan-logo-white.svg
  name: Changan Europe Status
  introTitle: "Changan Europe Service Monitor"
  introMessage: "Real-time monitoring and status updates for Changan Europe's digital platforms across the UK, Germany, and the Netherlands."
  navbar:
    - title: UK
      href: https://www.changaneurope.com/uk/
    - title: DE
      href: https://www.changaneurope.com/de/
    - title: NL
      href: https://www.changaneurope.com/nl/
  css: |
    :root {
      --primary-color: #002b5c;
      --nav-background-color: #002b5c;
      --nav-text-color: #ffffff;
      --body-background-color: #ffffff;
    }

    /* 1 & 3. Logo Positioning and Hiding Name */
    nav .logo {
      position: absolute !important;
      left: 20px !important;
      display: flex !important;
      align-items: center !important;
    }

    /* Specifically hides the "Changan Europe Status" text next to the logo */
    nav .logo div {
      display: none !important;
    }

    nav .logo img {
      height: 25px !important; /* Forces logo visibility */
      width: auto !important;
      filter: brightness(0) invert(1) !important; /* Backup: forces logo to white if SVG edit failed */
    }

    /* 2 & 4. Restore and Style the Blue Header Box */
    header {
      background-color: #ffffff !important; /* Page background stays white */
      padding: 60px 0 !important;
      display: block !important; /* Ensures the element isn't hidden */
      visibility: visible !important;
    }

    header h1, header p {
      background-color: var(--nav-background-color) !important;
      color: #ffffff !important;
      margin: 0 auto !important;
      max-width: 900px !important;
      text-align: center !important;
    }

    header h1 {
      padding: 40px 60px 10px 60px !important;
      border-radius: 8px 8px 0 0 !important;
      font-size: 2.2rem !important;
    }

    header p {
      padding: 0 60px 40px 60px !important;
      border-radius: 0 0 8px 8px !important;
      font-size: 1.1rem !important;
    }

    /* Navbar Centering */
    nav {
      justify-content: center !important;
      padding: 15px 0 !important;
    }

    nav a:not(.logo) {
      font-weight: bold !important;
      margin: 0 20px !important;
    }
